version: "3.8"

networks:
  lgtm-net:
    driver: bridge

services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=qdtbs
      - TZ=Europe/Istanbul
      - LANG=tr-TR.utf8
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=tr-TR
    restart: always
    networks:
      - lgtm-net

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "6831:6831/udp" # jaeger thrift/udp receiver
      - "14250:14250" # jaeger gRPC receiver (for Collector’s gRPC exporter)
      - "14268:14268" # jaeger HTTP Thrift endpoint
      - "16686:16686" # jaeger UI
    networks:
      - lgtm-net

  otel-collector:
    image: otel/opentelemetry-collector:0.84.0
    command: ["--config=/etc/custompath/otel-collector-config.yaml"]
    volumes:
      - type: bind
        source: /Users/bilgehanaygun/go-projects/urun/.deploy/otel-collector-config/otel-collector-config.yaml
        target: /etc/custompath/otel-collector-config.yaml
        read_only: true
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    networks:
      - lgtm-net
