version: "3.8"

networks:
  lgtm-net:
    driver: bridge
services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=qdtbs
      - TZ=Europe/Istanbul
      - LANG=tr-TR.utf8
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=tr-TR
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    command: ["--config=/etc/otel-collector/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector/config.yaml:ro
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # metrics/debug endpoint
    networks:
      - lgtm-net
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"
    networks:
      - lgtm-net
  mimir:
    image: grafana/mimir:2.2.0
    command: -config.file=/etc/mimir/local-config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/local-config.yaml:ro
    ports:
      - "9090:9090"
    networks:
      - lgtm-net
  tempo:
    image: grafana/tempo:1.7.1
    command: -config.file=/etc/tempo/local-config.yaml
    volumes:
      - ./tempo-config.yaml:/etc/tempo/local-config.yaml:ro
    ports:
      - "3200:3200"
    networks:
      - lgtm-net
  grafana:
    image: grafana/grafana:10.5.0
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - mimir
      - tempo
    networks:
      - lgtm-net
